### ISSUE TITLE
CapsLock as input source switch not working

### ISSUE THREAD

**Issue by Silencer** [AntonShevchuk/ukrainian-typography-keyboard-layout#4]
I try to use CapsLock to switch input source (MacOS Ventura 13.5) - but it not works with this UA layout (with default one it works). Also I look into info.plist file and there  key "TICapsLockLanguageSwitchCapable" if false, I try to change it into true but this doesn't help, maybe  you can advise something about how to resolve this situation - enable CapsLock switch?

**Comment by AntonShevchuk** [comment]
Hm, I try the following setup and it working

![telegram-cloud-photo-size-2-5370859365768218872-y](https://github.com/AntonShevchuk/ukrainian-typography-keyboard-layout/assets/142057/5082d001-47b1-4fad-bdb4-1b747725460b)

**Comment by Silencer** [comment]
The problem that it's not default apple keyboard, I'm using Logitech MX Keys, so it's not contains this globe key and it doesn't allow to select it for Caps Lock in specified menu, it's available only for internal apple keyboard. To use language switch for caps lock key I'm using another one "Keyboard" -> "Input Sources" ->  "Use Caps Lock ..." option .

**Comment by AntonShevchuk** [comment]
@Silencer can you check new build with external keyboard?
