### ISSUE TITLE
Impossible to type a question mark in Google Docs Document

### ISSUE THREAD

**Issue by alexandrpetrov** [AntonShevchuk/ukrainian-typography-keyboard-layout#9]
**Steps to reproduce:** open any text document in Google Docs. Place cursor somewhere in the document and press Option + .

**Expected result:** a question mark is typed

**Actual result:** Google docs Menus dropdown is opened.
<img width="365" alt="Screenshot 2024-06-12 at 20 22 07" src="https://github.com/AntonShevchuk/ukrainian-typography-keyboard-layout/assets/856669/26a3477d-2f9a-4a30-ab19-eaeeb53e6832">

**Comment by AntonShevchuk** [comment]
🤬 😡 😠 😤 😫 😮‍💨

**Comment by AntonShevchuk** [comment]
Added «?» to `⌥` + `7`
